### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by suyash-patil** [kaiiyer/rajappan#28]
@kaiiyer I would like to add CONTRIBUTING.md file.

**Comment by kaiiyer** [comment]
Go ahead @suyash-patil :zap:

**Comment by kaiiyer** [comment]
Logo
![image](https://user-images.githubusercontent.com/24914913/127732050-bd348cc2-5004-4640-a360-1458421128ab.png)
![image](https://user-images.githubusercontent.com/24914913/127732066-e1a647d5-25ed-449a-95a6-79712335ca59.png)
![image](https://user-images.githubusercontent.com/24914913/127732077-8406a7d0-5ead-48e4-bd8b-e2bc424a78d8.png)
